"""The original import entry is retained; the shared implementation is uniquely maintained by the lower module."""

from docvortex.content.markup import (
    AnchorTextNormalization as AnchorTextNormalization,
    AnchorVisibilityScope as AnchorVisibilityScope,
    ElementStyle as ElementStyle,
    FormulaDisplay as FormulaDisplay,
    FormulaExtraction as FormulaExtraction,
    FormulaSourceKind as FormulaSourceKind,
    MarkupAnchorDocument as MarkupAnchorDocument,
    MarkupAnchorPolicy as MarkupAnchorPolicy,
    MarkupAnchorRegistry as MarkupAnchorRegistry,
    MarkupContext as MarkupContext,
    MarkupProjector as MarkupProjector,
    MarkupStylesheet as MarkupStylesheet,
    ResolvedMarkupImage as ResolvedMarkupImage,
    TextStyle as TextStyle,
    TextStyleDelta as TextStyleDelta,
    canonical_anchor as canonical_anchor,
    element_id as element_id,
    extract_formula as extract_formula,
    strip_formula_delimiters as strip_formula_delimiters,
    visible_element_text as visible_element_text,
)

__all__ = [
    "AnchorTextNormalization",
    "AnchorVisibilityScope",
    "ElementStyle",
    "FormulaDisplay",
    "FormulaExtraction",
    "FormulaSourceKind",
    "MarkupAnchorDocument",
    "MarkupAnchorPolicy",
    "MarkupAnchorRegistry",
    "MarkupContext",
    "MarkupProjector",
    "MarkupStylesheet",
    "ResolvedMarkupImage",
    "TextStyle",
    "TextStyleDelta",
    "canonical_anchor",
    "element_id",
    "extract_formula",
    "strip_formula_delimiters",
    "visible_element_text",
]
