"""保留原有导入入口；共享实现由下层模块唯一维护。"""

from docvortex.content.markup.projector import (
    BLOCK_TAGS as BLOCK_TAGS,
    BlockType as BlockType,
    FormulaExtraction as FormulaExtraction,
    MarkupContext as MarkupContext,
    MarkupProjector as MarkupProjector,
    MarkupStylesheet as MarkupStylesheet,
    RAW_ALGORITHM as RAW_ALGORITHM,
    ResolvedMarkupImage as ResolvedMarkupImage,
    SKIPPED_TAGS as SKIPPED_TAGS,
    TextStyle as TextStyle,
    VISUAL_TYPE_MAPPING as VISUAL_TYPE_MAPPING,
    _CAPTION_TOKENS as _CAPTION_TOKENS,
    _FOOTNOTE_TOKENS as _FOOTNOTE_TOKENS,
    _InlineProjectionSegment as _InlineProjectionSegment,
    _InlineSpanDict as _InlineSpanDict,
    _LIST_PAGE_BLOCK_TAGS as _LIST_PAGE_BLOCK_TAGS,
    _MAX_TABLE_SPAN as _MAX_TABLE_SPAN,
    _VISUAL_ELEMENT_TAGS as _VISUAL_ELEMENT_TAGS,
    _WHITESPACE_RE as _WHITESPACE_RE,
    _XLINK_HREF as _XLINK_HREF,
    _append_inline_segment as _append_inline_segment,
    _append_list_block_content as _append_list_block_content,
    _raw_visual_type as _raw_visual_type,
    _semantic_tokens as _semantic_tokens,
    append_code_span as append_code_span,
    append_equation_span as append_equation_span,
    append_hyperlink_span as append_hyperlink_span,
    append_text_span as append_text_span,
    bounded_table_span as bounded_table_span,
    clean_text_node as clean_text_node,
    entity_text as entity_text,
    extend_inline_spans as extend_inline_spans,
    extract_formula as extract_formula,
    inline_span_plain_text as inline_span_plain_text,
    local_name as local_name,
    strip_span_dicts as strip_span_dicts,
    text_spans as text_spans,
    visible_raw_text_with_style as visible_raw_text_with_style,
    visible_text as visible_text,
)

__all__ = [
    "BLOCK_TAGS",
    "MarkupContext",
    "MarkupProjector",
    "ResolvedMarkupImage",
    "SKIPPED_TAGS",
    "bounded_table_span",
    "clean_text_node",
    "entity_text",
    "local_name",
    "visible_raw_text_with_style",
    "visible_text",
]
