"""跨库依赖可使用的模块与符号清单；修改此表意味着公开 API 变更。"""

PUBLIC_API: dict[str, tuple[str, ...]] = {
    "docvortex": (
        "analyze",
        "convert",
        "extract_metadata",
        "load_bundle",
        "parse",
    ),
    "docvortex.analyzers.native": (
        "CsvModel",
        "DocModel",
        "DocxModel",
        "EpubModel",
        "HtmlModel",
        "OdpModel",
        "OdsModel",
        "OdtModel",
        "OfdModel",
        "PdfModel",
        "PptModel",
        "PptxModel",
        "RtfModel",
        "XlsModel",
        "XlsxModel",
    ),
    "docvortex.analyzers.pdf": (
        "PDFTableRecoveryError",
        "PDFTablePage",
        "PDFTableResult",
        "PDFTextEvidence",
        "PDFTextLinkLine",
        "PDFTextLinkRange",
        "PDFTextScriptLine",
        "PDFTextScriptRange",
        "PDFTextStyleLine",
        "PDFTextStyleRange",
        "PDF_NATIVE_SCRIPT_MARKUP_KEY",
        "ScriptRole",
        "apply_text_evidence",
        "classify_char_script_roles",
        "prepare_table_page",
        "prepare_text_evidence",
        "project_table_text",
        "recover_table_region",
    ),
    "docvortex.api": (
        "analyze",
        "convert",
        "extract_metadata",
        "parse",
        "postprocess",
        "render",
    ),
    "docvortex.assets": (
        "ImageArray",
        "AssetStore",
        "ImageArtifact",
        "ImageFormat",
        "calculate_contrast",
        "crop_pil_image",
        "encode_crop_as_jpeg_data_uri",
        "image_size",
        "parse_image_data_uri_strict",
        "rotate_image_to_upright",
        "transcode_image",
        "validate_image_sidecar_path",
    ),
    "docvortex.content": ("normalize_pdf_model_text",),
    "docvortex.content.inline": (
        "inline_plain_text",
        "join_inline_spans",
    ),
    "docvortex.content.links": (
        "OFFICE_EXTERNAL_HYPERLINK_SCHEMES",
        "sanitize_hyperlink_target",
    ),
    "docvortex.content.spans": (
        "append_equation_span",
        "append_text_span",
        "inline_span_plain_text",
        "strip_span_dicts",
    ),
    "docvortex.content.table": (
        "build_row_rendered_cell_segments",
        "build_table_state_from_html",
        "calculate_row_rendered_segments",
        "can_merge_by_structure",
        "detect_table_headers",
        "expand_header_count_by_rowspan",
        "merge_table",
        "merge_table_content",
    ),
    "docvortex.content.text": (
        "build_tagged_formula_content",
        "clean_isolated_formula",
        "full_to_half",
        "full_to_half_exclude_marks",
        "is_hyphen_at_line_end",
        "merge_text_line_contents",
        "normalize_formula_content_for_tag",
        "normalize_formula_tag_content",
        "resolve_text_line_boundary",
    ),
    "docvortex.content.tree": ("iter_image_payloads",),
    "docvortex.document": (
        "detection",
        "page_range",
    ),
    "docvortex.document.contracts": ("HtmlSourceContext",),
    "docvortex.document.detection": (
        "guess_suffix_by_bytes",
        "guess_suffix_by_path",
    ),
    "docvortex.document.page_range": (
        "PAGE_RANGE_DESCRIPTION",
        "count_pages_in_range",
        "expand_page_range",
        "format_page_range",
        "get_end_page_id",
        "normalize_page_range_input",
        "normalize_result_page_range",
        "parse_page_range",
        "parse_page_range_set",
    ),
    "docvortex.document.pdf": (
        "Bbox",
        "Char",
        "Line",
        "PDFDocument",
        "PDFPage",
        "PDFPageTextGeometry",
        "PdfiumFontError",
        "PdfiumRuntimeInfo",
        "Span",
        "get_lines_from_chars",
        "images",
        "initialize_pdfium_runtime",
    ),
    "docvortex.document.pdf.images": (
        "DEFAULT_PDF_IMAGE_DPI",
        "ImageType",
        "crop_img",
        "get_crop_img",
        "get_crop_np_img",
        "load_images_from_pdf_bytes_range",
        "load_images_from_pdf_core",
        "pdf_page_to_image",
        "shutdown_pdf_render_executor",
    ),
    "docvortex.document.pdf.pdfium": (
        "pdfium_guard",
        "safe_rewrite_pdf_bytes_with_pdfium_result",
    ),
    "docvortex.document.pdf.visuals": (
        "attach_visual_block_images",
        "attach_visual_block_images_from_pdf",
    ),
    "docvortex.errors": (
        "DocumentError",
        "InvalidRequestError",
    ),
    "docvortex.geometry": (
        "bbox_center",
        "bbox_center_distance",
        "bbox_distance",
        "bbox_relative_pos",
        "bbox_to_quad",
        "calculate_overlap_area_2_minbox_area_ratio",
        "calculate_overlap_area_in_bbox1_area_ratio",
        "convert_bbox",
        "normalize_bbox",
        "normalize_quarter_turn_angle",
        "normalize_to_int_bbox",
        "rotate_bbox",
    ),
    "docvortex.options": (
        "LatexDelimiterConfig",
        "LatexDelimitersConfig",
    ),
    "docvortex.postprocess.document": ("model_json_to_middle_json",),
    "docvortex.render.contracts": (
        "AssetResolver",
        "DocxRenderOptions",
        "EpubRenderOptions",
        "HtmlRenderOptions",
        "ImageRenderer",
        "LatexRenderOptions",
        "MarkdownRenderOptions",
        "PdfRenderOptions",
        "RenderMode",
        "StructuredContentRenderOptions",
    ),
    "docvortex.render.docx": (
        "DocxRenderError",
        "render_docx",
    ),
    "docvortex.render.epub": ("render_epub",),
    "docvortex.render.fragments": (
        "format_embedded_html",
        "normalize_image_source",
        "parse_list_item_marker",
        "render_inline_content",
        "render_internal_link",
        "resolve_image_source",
        "strip_index_page_tail",
    ),
    "docvortex.render.html": ("render_html",),
    "docvortex.render.latex": ("render_latex",),
    "docvortex.render.markdown": (
        "build_markdown_image",
        "render_markdown",
        "render_single_block",
    ),
    "docvortex.render.pdf": ("render_pdf",),
    "docvortex.render.structured_content": ("render_structured_content",),
    "docvortex.schema": (
        "AlgorithmBodyBlock",
        "BBox",
        "BLOCK_ADAPTER",
        "BLOCK_TYPES",
        "Block",
        "BlockBase",
        "BlockType",
        "BlockTypes",
        "ChartAnnotationBlock",
        "ChartBlock",
        "ChartBodyBlock",
        "ChartChildBlock",
        "CodeAnnotationBlock",
        "CodeBlock",
        "CodeBodyBlock",
        "CodeChildBlock",
        "CodeInlineSpan",
        "ContinuableTextBlockBase",
        "DocTitleBlock",
        "DocumentMetadata",
        "DocumentModel",
        "DocumentProperties",
        "EquationBlock",
        "EquationInlineSpan",
        "FILE_SUFFIXES",
        "FileSuffix",
        "HyperlinkSpan",
        "INLINE_SPAN_ADAPTER",
        "INLINE_SPAN_LIST_ADAPTER",
        "INLINE_STYLE_ORDER",
        "ImageAnnotationBlock",
        "ImageBlock",
        "ImageBodyBlock",
        "ImageChildBlock",
        "ImagePayloadBlock",
        "ImagePayloadContentBlock",
        "IndexBlock",
        "IndexChildBlock",
        "InlineContentBlock",
        "InlineSpan",
        "InlineStyle",
        "IntBBox",
        "ListBlock",
        "ListChildBlock",
        "MERGE_TRANSPARENT_BLOCK_TYPES",
        "MiddleJson",
        "ModelJson",
        "NonLinkInlineSpan",
        "PAGE_AUXILIARY_BLOCK_TYPES",
        "PAGE_BLOCK_TYPES",
        "PageAuxTextBlock",
        "PageBlock",
        "PageBlockTypes",
        "PageFootnoteBlock",
        "PageInfo",
        "ParagraphTitleBlock",
        "Producer",
        "RAW_ALGORITHM",
        "RAW_CAPTION",
        "RAW_FOOTNOTE",
        "RAW_FORMULA_NUMBER",
        "RAW_ONLY_BLOCK_TYPES",
        "RAW_PHONETIC",
        "RawBlockType",
        "RefTextBlock",
        "StringContentBlock",
        "TableAnnotationBlock",
        "TableBlock",
        "TableBodyBlock",
        "TableChildBlock",
        "TextBlock",
        "TextSpan",
        "TitleBlockBase",
        "VISUAL_MAIN_TYPES",
        "VISUAL_RELATION_IGNORED_TYPES",
        "VISUAL_TYPE_MAPPING",
        "parse_block",
        "parse_inline_span",
        "parse_inline_spans",
    ),
    "docvortex.visualization": ("render_layout_pdf",),
}

__all__ = ["PUBLIC_API"]
