"""DOCX renderer Security picture material analysis and format preparation."""

from __future__ import annotations

import re
from dataclasses import dataclass
from io import BytesIO
from pathlib import PurePosixPath
from urllib.parse import urlsplit

from PIL import Image, UnidentifiedImageError

from ....foundation._image_payload import (
    extract_generated_svg_fallback,
    parse_image_data_uri_strict,
    validate_image_sidecar_path,
)
from ....schema import ImagePayloadBlock
from ...contracts import AssetResolver

_PIL_FORMAT_EXTENSIONS = {
    "BMP": "bmp",
    "GIF": "gif",
    "JPEG": "jpg",
    "PNG": "png",
    "TIFF": "tiff",
    "WEBP": "webp",
}
_EXTENSION_ALIASES = {
    "jpeg": "jpg",
    "jpe": "jpg",
    "tif": "tiff",
}
_SVG_START_RE = re.compile(rb"^(?:\xef\xbb\xbf)?\s*(?:<\?xml\b.*?\?>\s*)?<svg\b", re.IGNORECASE | re.DOTALL)


class DocxAssetError(ValueError):
    """Indicates DOCX renderer The image material cannot be safely loaded or recognized."""


@dataclass(frozen=True, slots=True)
class PreparedImage:
    """Save image bytes, format and pixel dimensions that can be passed directly to DOCX."""

    data: bytes
    extension: str
    width_px: int
    height_px: int
    svg_data: bytes | None = None


def prepare_block_image(
    block: ImagePayloadBlock,
    asset_resolver: AssetResolver | None = None,
) -> PreparedImage:
    """Load images from image payload block, selected by common priority of sidecar, data URI."""
    if not isinstance(block, ImagePayloadBlock):
        raise TypeError("block must be an ImagePayloadBlock")
    if block.image_path is not None:
        return _prepare_relative_asset(block.image_path, asset_resolver)
    if block.image_base64 is not None:
        return _prepare_data_uri(block.image_base64)
    raise DocxAssetError("Image block does not contain image_base64 or image_path")


def prepare_html_image(
    source: str,
    asset_resolver: AssetResolver | None = None,
) -> PreparedImage:
    """Load data URI or safe relative sidecar pictures from HTML ``img``'s src."""
    if not isinstance(source, str):
        raise TypeError("HTML image source must be a string")
    normalized_source = source.strip()
    if not normalized_source:
        raise DocxAssetError("HTML image source must not be empty")
    if normalized_source.lower().startswith("data:"):
        if not normalized_source.lower().startswith("data:image/"):
            raise DocxAssetError("Only image data URIs are supported")
        return _prepare_data_uri(normalized_source)
    return _prepare_relative_asset(normalized_source, asset_resolver)


def prepare_image_bytes(
    data: bytes,
    *,
    declared_extension: str | None = None,
) -> PreparedImage:
    """Strictly decode the picture bytes and convert WebP, which is not directly supported by Word, into PNG in memory."""
    if not isinstance(data, bytes):
        raise DocxAssetError("Image resolver must return bytes")
    if not data:
        raise DocxAssetError("Image payload must not be empty")

    expected_extension = _normalize_extension(declared_extension)
    if expected_extension == "svg" or _looks_like_svg(data):
        try:
            fallback, logical_width, logical_height = extract_generated_svg_fallback(data)
        except ValueError as exc:
            raise DocxAssetError("SVG images are not supported unless they are safely generated by DocVortex") from exc
        prepared = prepare_image_bytes(fallback, declared_extension="png")
        return PreparedImage(
            data=prepared.data,
            extension=prepared.extension,
            width_px=logical_width,
            height_px=logical_height,
            svg_data=data,
        )

    try:
        with Image.open(BytesIO(data)) as image:
            detected_extension = _PIL_FORMAT_EXTENSIONS.get((image.format or "").upper())
            if detected_extension is None:
                raise DocxAssetError(f"Unsupported image format: {image.format or 'unknown'}")
            width_px, height_px = image.size
            image.load()
            if expected_extension is not None and expected_extension != detected_extension:
                raise DocxAssetError(
                    f"Image bytes do not match declared format: expected {expected_extension}, detected {detected_extension}"
                )
            if detected_extension == "webp":
                return _convert_webp_to_png(image, width_px, height_px)
    except DocxAssetError:
        raise
    except (UnidentifiedImageError, OSError, ValueError) as exc:
        raise DocxAssetError("Invalid or corrupted image payload") from exc

    return PreparedImage(
        data=data,
        extension=detected_extension,
        width_px=width_px,
        height_px=height_px,
    )


def _prepare_data_uri(data_uri: str) -> PreparedImage:
    """Strictly parse data URI, and verify MIME, signature and complete image data."""
    try:
        data, extension = parse_image_data_uri_strict(data_uri)
    except ValueError as exc:
        raise DocxAssetError(str(exc)) from exc
    return prepare_image_bytes(data, declared_extension=extension)


def _prepare_relative_asset(
    image_path: str,
    asset_resolver: AssetResolver | None,
) -> PreparedImage:
    """Verifies that relative sidecar paths read bytes through the caller resolver without accessing the file system or network."""
    parsed_source = urlsplit(image_path)
    if parsed_source.scheme or parsed_source.netloc:
        raise DocxAssetError(f"Remote or scheme-based image source is not supported: {image_path}")
    try:
        safe_path = validate_image_sidecar_path(image_path)
    except ValueError as exc:
        raise DocxAssetError(str(exc)) from exc
    if asset_resolver is None:
        raise DocxAssetError(f"asset_resolver is required for image_path: {safe_path}")
    try:
        data = asset_resolver(safe_path)
    except Exception as exc:
        raise DocxAssetError(f"Failed to resolve image asset: {safe_path}") from exc

    extension = PurePosixPath(safe_path).suffix.removeprefix(".") or None
    return prepare_image_bytes(data, declared_extension=extension)


def _normalize_extension(extension: str | None) -> str | None:
    """Normalize recognized extensions; unknown extensions are not declared as image formats."""
    if extension is None:
        return None
    normalized = extension.lower().lstrip(".").split("+", 1)[0]
    normalized = _EXTENSION_ALIASES.get(normalized, normalized)
    if normalized == "svg":
        return normalized
    return normalized if normalized in set(_PIL_FORMAT_EXTENSIONS.values()) else None


def _looks_like_svg(data: bytes) -> bool:
    """Identifies the SVG byte with the optional BOM/XML declaration to give an explicit unsupported error."""
    return _SVG_START_RE.match(data[:4096]) is not None


def _convert_webp_to_png(image: Image.Image, width_px: int, height_px: int) -> PreparedImage:
    """Convert decoded WebP to PNG in memory, preserving transparency channels and pixel dimensions."""
    output = BytesIO()
    image.save(output, format="PNG")
    return PreparedImage(
        data=output.getvalue(),
        extension="png",
        width_px=width_px,
        height_px=height_px,
    )


__all__ = [
    "AssetResolver",
    "DocxAssetError",
    "PreparedImage",
    "prepare_block_image",
    "prepare_html_image",
    "prepare_image_bytes",
]
