"""验证非 HTML 生成标识与用户显式标题的品牌边界。"""

from __future__ import annotations

from io import BytesIO
from zipfile import ZipFile

from pypdf import PdfReader

from docvortex.render.docx import render_docx
from docvortex.render.latex import render_latex
from docvortex.render.pdf import render_pdf
from docvortex.schema import MiddleJson, PageInfo, TextBlock, TextSpan


def test_non_html_renderers_use_new_owned_identifiers() -> None:
    """PDF 元数据、DOCX 样式和 LaTeX 宏统一新品牌，用户标题则保持原文。"""
    document = MiddleJson(
        pages=[PageInfo(page_idx=0, blocks=[TextBlock(type="text", index=0, content=[TextSpan(type="text", content="Body")])])],
        metadata={"file_suffix": "html", "producer": {"name": "docvortex", "version": "0.2.0"}},
        is_full_document=True,
    )
    metadata = PdfReader(BytesIO(render_pdf(document))).metadata
    assert metadata.title == "DocVortex Document"
    assert metadata.author == "DocVortex"
    assert metadata.creator == "DocVortex PDF Renderer"
    with ZipFile(BytesIO(render_docx(document))) as archive:
        styles = archive.read("word/styles.xml").decode()
        assert "DocVortex Code" in styles
        assert "MinerU" not in styles and "DocGale" not in styles
    latex = render_latex(document)
    assert "Generated by DocVortex" in latex
    assert r"\DocVortexLineBreak" in latex
    assert "MinerU" not in latex and "DocGale" not in latex
    explicit = "DocGale user title"
    assert PdfReader(BytesIO(render_pdf(document, document_title=explicit))).metadata.title == explicit
    assert explicit in render_latex(document, document_title=explicit)
