"""Read-only content preparation and bounded measurement cache for a single PDF table, no shared variable trial objects."""

from __future__ import annotations

from copy import copy
from collections import OrderedDict
from dataclasses import dataclass
from math import isfinite
from typing import Callable

from bs4 import Tag
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.platypus import Paragraph

from ....schema import InlineSpan, TextSpan
from ..common.html_table import HtmlTableGrid, HtmlTableSource
from .styles import PdfStyleSet


@dataclass(frozen=True, slots=True)
class _TextTemplate:
    """Save ordinary text fragments that never participate in line breaks, and only give independent copies to candidate paragraphs."""

    key: tuple
    fragments: tuple
    word_wrap: str | None
    paragraph_type: type[Paragraph]


@dataclass
class PreparedCell:
    """Preserves the parsed cell contents, as well as the most recent set of plain text fragments that have not yet been wrap."""

    spans: list[InlineSpan]
    images: tuple[tuple[str, str], ...]
    nested: tuple[Tag, ...]
    template: Paragraph | None = None
    template_key: tuple | None = None
    text_template: _TextTemplate | None = None

    @property
    def plain(self) -> bool:
        """Only normal text can safely reuse parsed fragments, and positioning diagnostics generated by formulas or links will not be skipped."""
        return not self.images and not self.nested and all(isinstance(span, TextSpan) for span in self.spans)

    @property
    def unstyled(self) -> bool:
        """Excluding styles such as superscripts and subscripts related to font sizes, only bare text fragments can be reused across font sizes."""
        return self.plain and not any(span.styles for span in self.spans)

    def _text_paragraph(self, build: Callable, style: ParagraphStyle, width: float, key: tuple) -> Paragraph:
        """Only respecifies the target font size, inheriting the current style's leading, without approximating scaling font measurements."""
        template = self.text_template
        if template is None or template.key != key:
            paragraph = build(self.spans or [TextSpan(type="text", content=" ")], style, width)
            if paragraph.bulletText or any(hasattr(fragment, "cbDefn") for fragment in paragraph.frags):
                return paragraph
            template = self.text_template = _TextTemplate(
                key, tuple(paragraph.frags), paragraph.style.wordWrap, type(paragraph)
            )
        actual_style = (
            style.clone(style.name + " CJK", wordWrap="CJK")
            if template.word_wrap == "CJK" and style.wordWrap != "CJK"
            else style
        )
        fragments = []
        for source in template.fragments:
            fragment = copy(source)
            fragment.fontSize = style.fontSize
            # Normal text still has empty decoration/link lists, candidates cannot modify these lists for templates or other candidates.
            for name in ("us_lines", "link"):
                value = getattr(fragment, name, None)
                if isinstance(value, list):
                    setattr(fragment, name, value.copy())
            fragments.append(fragment)
        return template.paragraph_type("", actual_style, frags=fragments)

    def paragraph(
        self,
        build: Callable,
        style: ParagraphStyle,
        width: float,
        key: tuple,
        *,
        consume: bool,
        fragment_key: tuple | None = None,
    ) -> Paragraph:
        """Copy the fragment from the text template that was not involved in the rehearsal; each candidate gets independent Paragraph and fragment."""
        if not self.plain:
            return build(self.spans, style, width)
        if fragment_key is not None and self.unstyled:
            return self._text_paragraph(build, style, width, fragment_key)
        if self.template is None or self.template_key != key:
            spans = self.spans or [TextSpan(type="text", content=" ")]
            self.template = build(spans, style, width)
            self.template_key = key
        template = self.template
        if consume:
            # After the column width measurement is completed, hand the template without wrap to the actual cell to avoid holding the template and the final paragraph at the same time.
            self.template = None
            self.template_key = None
            return template
        return type(template)(
            "", template.style, bulletText=template.bulletText, frags=[copy(fragment) for fragment in template.frags]
        )


class PdfTableContent:
    """Binds the parse tree of a single table; the cache only exists once during the renderer life cycle."""

    def __init__(self, source: HtmlTableSource) -> None:
        """Preflight top-level HTML, nested grids and cells prepared as first use, preserving existing exception order."""
        self.source = source
        self._grids: dict[str | int, tuple[HtmlTableGrid, ...]] = {}
        self._cells: dict[int, PreparedCell] = {}
        self._styles: dict[int, tuple[ParagraphStyle, tuple, tuple]] = {}
        self.widths: dict[tuple, tuple[float, float]] = {}
        self._glyphs: OrderedDict[tuple[str, float, str], float] = OrderedDict()
        self._height_bound: tuple[tuple, int | None] | None = None
        self.grids(source)

    def grids(self, source: HtmlTableSource) -> tuple[HtmlTableGrid, ...]:
        """Reuse the same original string or surviving nested Tag to avoid repeated parsing of placeholder grids for each font size."""
        from .table import parse_html_tables

        key = source if isinstance(source, str) else id(source)
        if key not in self._grids:
            self._grids[key] = parse_html_tables(source)
        return self._grids[key]

    def style_key(self, style: ParagraphStyle) -> tuple:
        """Calculate the complete signature for the currently constructed body and header styles, and only temporarily store the most recent two sets of styles."""
        cached = self._styles.get(id(style))
        if cached is not None:
            return cached[1]
        key = tuple(sorted((name, repr(value)) for name, value in vars(style).items()))
        if len(self._styles) >= 2:
            self._styles.pop(next(iter(self._styles)))
        self._styles[id(style)] = (
            style,
            key,
            tuple((name, value) for name, value in key if name not in ("fontSize", "leading")),
        )
        return key

    def fragment_key(self, style: ParagraphStyle) -> tuple:
        """Each set of styles only calculates the font size-independent signature once, and other attributes such as font and color are still involved in the failure judgment."""
        self.style_key(style)
        return self._styles[id(style)][2]

    def begin_build(self) -> None:
        """The styles are re-captured every time the layout is tried, and the old width or fragment cache will not be hit after updating the styles externally."""
        self._styles.clear()

    def unstyled_grids(self) -> tuple[HtmlTableGrid, ...] | None:
        """Only tables without resources, links, and rich text are eligible for deterministic trial optimization."""
        grids = self.grids(self.source)
        if all(self.cell(cell.tag).unstyled for grid in grids for cell in grid.cells):
            return grids
        return None

    def minimum_height(self, font_size: float, styles: PdfStyleSet) -> float | None:
        """Only count a line that can be proven to contain text, and do not make overly strong inferences on blank lines, merged lines, and rich content."""
        from .inline import _font_for_character
        from .table import _spatial_leading, _SPATIAL_VERTICAL_PADDING

        key = (repr(vars(styles.table_cell)), repr(vars(styles.table_header)))
        if self._height_bound is None or self._height_bound[0] != key:
            count = None
            try:
                grids = self.unstyled_grids()
                if grids is not None and len(grids) == 1 and not any(cell.rowspan > 1 for cell in grids[0].cells):
                    visible_rows = set()
                    for cell in grids[0].cells:
                        if cell.row in visible_rows:
                            continue
                        style = styles.table_header if cell.is_header else styles.table_cell
                        for span in self.cell(cell.tag).spans:
                            if any(
                                character.isalnum()
                                and isfinite(
                                    advance := pdfmetrics.stringWidth(
                                        character, _font_for_character(character) or style.fontName, style.fontSize
                                    )
                                )
                                and advance > 0
                                for character in span.content
                            ):
                                visible_rows.add(cell.row)
                                break
                    count = len(visible_rows)
            except Exception:
                # When the optimization qualification judgment fails, return to the actual structure, allowing the original process to retain the original exception and positioning information.
                count = None
            self._height_bound = (key, count)
        count = self._height_bound[1]
        if count is None:
            return None
        height = count * (_spatial_leading(font_size) + 2 * _SPATIAL_VERTICAL_PADDING)
        return height if isfinite(height) else None

    def cell(self, tag: Tag) -> PreparedCell:
        """Prepare text, image references and directly nested tables cell by cell, retaining the original order and filtering rules."""
        from .table import _html_cell_spans

        key = id(tag)
        if key not in self._cells:
            images = []
            for image in tag.find_all("img"):
                if image.find_parent("table") is not tag.find_parent("table"):
                    continue
                source = image.get("src", "")
                alt = image.get("alt", "image")
                images.append(
                    (
                        "" if isinstance(source, list) else str(source),
                        " ".join(str(item) for item in alt) if isinstance(alt, list) else str(alt),
                    )
                )
            nested = tuple(table for table in tag.find_all("table") if table.find_parent(("td", "th")) is tag)
            self._cells[key] = PreparedCell(_html_cell_spans(tag), tuple(images), nested)
        return self._cells[key]

    def remember_widths(self, key: tuple, value: tuple[float, float]) -> None:
        """Only caches the inherent width of scalars, limiting the extra memory for long tables and multi-font sizes."""
        if len(self.widths) >= 4096 and key not in self.widths:
            self.widths.pop(next(iter(self.widths)))
        self.widths[key] = value

    def character_width(self, font_name: str, font_size: float, character: str) -> float:
        """Reuse native font widths at exact font, size and character, without scaling, and save up to 4096 items."""
        key = (font_name, font_size, character)
        if key in self._glyphs:
            self._glyphs.move_to_end(key)
            return self._glyphs[key]
        width = pdfmetrics.stringWidth(character, font_name, font_size)
        if len(self._glyphs) >= 4096:
            self._glyphs.popitem(last=False)
        self._glyphs[key] = width
        return width

    def release_templates(self) -> None:
        """The formatted page releases the parse tree and template, and subsequent pages that have not yet been trial-typed still retain the grid parsed once."""
        if self._cells:
            self._cells.clear()
            self._grids.clear()
        self.widths.clear()
        self._styles.clear()
        self._glyphs.clear()
        self._height_bound = None
