"""Strictly MiddleJson to TeX Live XeLaTeX Rendering implementation of full documentation."""

from __future__ import annotations

import re

from bs4 import BeautifulSoup
from loguru import logger

from ....content.inline import inline_plain_text
from ....schema import (
    PAGE_AUXILIARY_BLOCK_TYPES,
    RAW_ALGORITHM,
    AlgorithmBodyBlock,
    BlockType,
    ChartAnnotationBlock,
    ChartBlock,
    ChartBodyBlock,
    CodeAnnotationBlock,
    CodeBlock,
    CodeBodyBlock,
    DocTitleBlock,
    EquationBlock,
    ImageAnnotationBlock,
    ImageBlock,
    ImageBodyBlock,
    ImagePayloadBlock,
    IndexBlock,
    InlineSpan,
    ListBlock,
    MiddleJson,
    PageFootnoteBlock,
    ParagraphTitleBlock,
    RefTextBlock,
    TableAnnotationBlock,
    TableBlock,
    TableBodyBlock,
    TextBlock,
    TitleBlockBase,
)
from ..common.index import strip_index_page_tail
from ..common.list_items import ListItem, parse_list_item_marker, reference_list_needs_bullets
from ..common.planner import PlannedBlock, build_render_plan
from .assets import normalize_asset_base_path, remote_block_image_url, resolve_block_image_path, tex_image_path
from .inline import LatexAnchorRegistry, escape_latex_text, escape_latex_url, render_inline_spans, render_joined_inline_contents
from .table import LatexTableError, LatexTableRenderer

_HTML_TABLE_RE = re.compile(r"<\s*table\b", re.IGNORECASE)
_TOP_LEVEL_DISPLAY_ENV_RE = re.compile(
    r"^\s*\\begin\{(?P<name>align\*?|equation\*?|gather\*?|multline\*?)\}",
    re.DOTALL,
)
_PREAMBLE_LINES = (
    "% !TeX program = xelatex",
    "% Generated by DocVortex. Compile with: latexmk -xelatex <file>.tex",
    r"\documentclass[UTF8,fontset=fandol,11pt]{ctexart}",
    r"\usepackage[a4paper,margin=20mm]{geometry}",
    r"\usepackage{amsmath,amssymb}",
    r"\usepackage{graphicx}",
    r"\usepackage{longtable}",
    r"\usepackage{array}",
    r"\usepackage{booktabs}",
    r"\usepackage{multirow}",
    r"\usepackage{enumitem}",
    r"\usepackage[table]{xcolor}",
    r"\usepackage[normalem]{ulem}",
    r"\usepackage{xeCJKfntef}",
    r"\usepackage{fvextra}",
    r"\usepackage[unicode,hidelinks]{hyperref}",
    r"\definecolor{DocVortexGray}{HTML}{6B7280}",
    r"\definecolor{DocVortexSurface}{HTML}{F3F4F6}",
    r"\definecolor{DocVortexTableHeader}{HTML}{E5E7EB}",
    r"\setlength{\parindent}{2em}",
    r"\setlength{\parskip}{0.4em}",
    r"\setlist{leftmargin=*,nosep}",
    r"\setlength{\LTpre}{0.4em}",
    r"\setlength{\LTpost}{0.6em}",
    r"\newcommand{\DocVortexLineBreak}{\leavevmode\hfill\break}",
    r"\newcommand{\DocVortexPlaceholder}[1]{\fcolorbox{DocVortexGray}{DocVortexSurface}{\textit{#1}}}",
)


class _LatexRenderer:
    """Save the deterministic state required for a complete LaTeX document rendering."""

    def __init__(
        self,
        middle_json: MiddleJson,
        *,
        asset_base_path: str,
        document_title: str | None,
    ) -> None:
        """Initialize shared planner, anchor, table and code environment contexts."""
        self.middle_json = middle_json
        self.asset_base_path = normalize_asset_base_path(asset_base_path)
        self.document_title = _resolve_document_title(middle_json, document_title)
        self.anchors = LatexAnchorRegistry(_collect_anchor_targets(middle_json))
        self.tables = LatexTableRenderer(asset_base_path=self.asset_base_path, anchors=self.anchors)
        self.verbatim_counter = 0

    def render(self) -> str:
        """Generate complete source code including fixed TeX Live preamble area and text environment."""
        rendered_blocks: list[str] = []
        for page in build_render_plan(self.middle_json):
            for planned in page:
                if planned.removed or planned.block.type in PAGE_AUXILIARY_BLOCK_TYPES:
                    continue
                rendered = self._render_planned_block(planned)
                if rendered.strip():
                    rendered_blocks.append(rendered.strip("\n"))
        title = escape_latex_text(self.document_title, preserve_newlines=False)
        lines = [*_PREAMBLE_LINES, rf"\hypersetup{{pdftitle={{{title}}}}}", r"\begin{document}"]
        if rendered_blocks:
            lines.extend(("", "\n\n".join(rendered_blocks), ""))
        lines.append(r"\end{document}")
        return "\n".join(lines) + "\n"

    def _render_planned_block(self, planned: PlannedBlock) -> str:
        """Distributes LaTeX renderings as strictly PageBlock specific types."""
        block = planned.block
        if isinstance(block, TextBlock):
            content = render_joined_inline_contents(planned.text_contents or [block.content], self.anchors)
            return self._anchored_paragraph(content, block.anchor)
        if isinstance(block, RefTextBlock):
            content = render_joined_inline_contents(planned.text_contents or [block.content], self.anchors)
            return _paragraph(content)
        if isinstance(block, (DocTitleBlock, ParagraphTitleBlock)):
            return self._render_title(block)
        if isinstance(block, PageFootnoteBlock):
            return self._render_page_footnote(block)
        if isinstance(block, EquationBlock):
            return self._render_equation(block)
        if isinstance(block, ListBlock):
            return self._render_list(block)
        if isinstance(block, IndexBlock):
            return self._render_index(block)
        if isinstance(block, ImageBlock):
            return self._render_image_block(block)
        if isinstance(block, TableBlock):
            return self._render_table_block(block)
        if isinstance(block, ChartBlock):
            return self._render_chart_block(block)
        if isinstance(block, CodeBlock):
            return self._render_code_block(block)
        raise TypeError(f"Unsupported PageBlock type: {type(block).__name__}")

    def _anchored_paragraph(self, content: str, anchor: str | None) -> str:
        """Adds first occurrence of document-level hypertarget to visible text."""
        if not content.strip():
            return ""
        target = self.anchors.emit_target(anchor)
        return "\n".join(part for part in (target, _paragraph(content)) if part)

    def _render_title(self, block: DocTitleBlock | ParagraphTitleBlock) -> str:
        """Map the global title hierarchy to the unnumbered LaTeX title command."""
        content = render_inline_spans(block.content, self.anchors)
        if not content.strip():
            return ""
        target = self.anchors.emit_target(block.anchor)
        command = {
            1: "section",
            2: "subsection",
            3: "subsubsection",
            4: "paragraph",
            5: "subparagraph",
        }.get(block.level)
        heading = rf"\{command}*{{{content}}}" if command is not None else rf"\par\noindent{{\small\bfseries {content}}}\par"
        return "\n".join(part for part in (target, heading) if part)

    def _render_page_footnote(self, block: PageFootnoteBlock) -> str:
        """Keep page footers as addressable blocks of gray text in small font size."""
        content = render_inline_spans(block.content, self.anchors)
        if not content.strip():
            return ""
        target = self.anchors.emit_target(block.anchor)
        footnote = rf"{{\footnotesize\color{{DocVortexGray}} {content}\par}}"
        return "\n".join(part for part in (target, footnote) if part)

    def _render_equation(self, block: EquationBlock) -> str:
        """Output block-level LaTeX as is; empty formulas are rolled back in sidecar and occupancy order."""
        content = block.content.strip()
        if content:
            return _wrap_display_formula(content)
        if not _has_image_payload(block):
            return self._placeholder("formula unavailable") + r"\par"
        return self._render_image_payload(block, alt_text="formula")

    def _render_list(self, block: ListBlock) -> str:
        """Recursively output a list of native or explicit tags sorted by shared marker."""
        parsed_leaves = [
            parse_list_item_marker(child.content)
            for child in block.content
            if not isinstance(child, ListBlock) and inline_plain_text(child.content).strip()
        ]
        add_reference_bullets = reference_list_needs_bullets(block)
        environment, kind = _classify_list(parsed_leaves, add_reference_bullets)
        options = "[leftmargin=*,nosep]"
        if environment == "description":
            options = "[style=nextline,leftmargin=3em,nosep]"
        lines = [rf"\begin{{{environment}}}{options}"]
        has_item = False
        for child in block.content:
            if isinstance(child, ListBlock):
                nested = self._render_list(child)
                if nested:
                    if not has_item:
                        lines.append(r"\item[]")
                        has_item = True
                    lines.append(nested)
                continue
            parsed = parse_list_item_marker(child.content)
            item_spans, label = _list_item_content(parsed, child.content, kind, add_reference_bullets)
            content = render_inline_spans(item_spans, self.anchors) or "~"
            if environment == "description" or label is not None:
                rendered_label = escape_latex_text(label or "", preserve_newlines=False)
                lines.append(rf"\item[{{{rendered_label}}}] {content}")
            else:
                lines.append(rf"\item {content}")
            has_item = True
        lines.append(rf"\end{{{environment}}}")
        return "\n".join(lines) if has_item else ""

    def _render_index(self, block: IndexBlock) -> str:
        """Recursively output the in-text directories and link only the real anchor target."""
        lines = [r"\begin{itemize}[leftmargin=*,nosep]"]
        has_item = False
        for child in block.content:
            if isinstance(child, IndexBlock):
                nested = self._render_index(child)
                if nested:
                    if not has_item:
                        lines.append(r"\item[]")
                        has_item = True
                    lines.append(nested)
                continue
            content = strip_index_page_tail(child.content)
            label = render_inline_spans(content, self.anchors).strip()
            if not label:
                continue
            target = self.anchors.target_for(child.anchor)
            if target is not None:
                label = rf"\hyperlink{{{target}}}{{{label}}}"
            lines.append(rf"\item {label}")
            has_item = True
        lines.append(r"\end{itemize}")
        return "\n".join(lines) if has_item else ""

    def _render_image_block(self, block: ImageBlock) -> str:
        """Output the image body and description text in original sub-block order."""
        parts: list[str] = []
        for child in block.content:
            if isinstance(child, ImageBodyBlock):
                alt = _plain_html_text(child.content) or block.sub_type or "image"
                parts.append(self._render_image_payload(child, alt_text=alt))
            elif isinstance(child, ImageAnnotationBlock):
                parts.append(self._render_annotation(child))
            else:
                raise TypeError(f"Unsupported image child: {type(child).__name__}")
        return _join_parts(parts)

    def _render_table_block(self, block: TableBlock) -> str:
        """Prioritize output of native longtable, and then fall back to images, visible text or placeholders."""
        parts: list[str] = []
        for child in block.content:
            if isinstance(child, TableBodyBlock):
                parts.append(self._render_table_body(child))
            elif isinstance(child, TableAnnotationBlock):
                parts.append(self._render_annotation(child))
            else:
                raise TypeError(f"Unsupported table child: {type(child).__name__}")
        return _join_parts(parts)

    def _render_table_body(self, block: TableBodyBlock) -> str:
        """Fixed fallback chain for executing structured tables to sidecar, text, placeholders."""
        content = block.content.strip()
        if content and _HTML_TABLE_RE.search(content):
            try:
                return self.tables.render(content)
            except LatexTableError as exc:
                logger.warning("LaTeX HTML table fallback: {}", exc)
            image = self._render_local_image(block)
            if image:
                return image
            plain = _plain_html_text(content)
            if plain:
                return self._render_verbatim(plain)
            return self._placeholder("table unavailable")
        if content:
            return self._render_verbatim(block.content)
        if not _has_image_payload(block):
            return self._placeholder("table unavailable") + r"\par"
        return self._render_image_payload(block, alt_text="table")

    def _render_chart_block(self, block: ChartBlock) -> str:
        """Retain the chart image and continue outputting the materializable structured table."""
        parts: list[str] = []
        for child in block.content:
            if isinstance(child, ChartBodyBlock):
                body_parts: list[str] = []
                has_image_payload = bool(child.image_path or child.image_base64 or child.image_url)
                local_image = self._render_local_image(child)
                if local_image:
                    body_parts.append(local_image)
                elif has_image_payload:
                    body_parts.append(self._render_image_payload(child, alt_text=block.sub_type or "chart"))
                content = child.content.strip()
                if content and _HTML_TABLE_RE.search(content):
                    try:
                        body_parts.append(self.tables.render(content))
                    except LatexTableError as exc:
                        logger.warning("LaTeX chart table fallback: {}", exc)
                        plain = _plain_html_text(content)
                        if plain:
                            body_parts.append(_paragraph(escape_latex_text(plain)))
                elif content and not local_image:
                    body_parts.append(_paragraph(escape_latex_text(_plain_html_text(content))))
                elif not has_image_payload and not content:
                    body_parts.append(self._placeholder("chart unavailable"))
                parts.append(_join_parts(body_parts))
            elif isinstance(child, ChartAnnotationBlock):
                parts.append(self._render_annotation(child))
            else:
                raise TypeError(f"Unsupported chart child: {type(child).__name__}")
        return _join_parts(parts)

    def _render_code_block(self, block: CodeBlock) -> str:
        """Output blank code or algorithm text containing formulas and descriptions."""
        parts: list[str] = []
        for child in block.content:
            if isinstance(child, CodeBodyBlock):
                if block.sub_type != BlockType.CODE:
                    raise TypeError("code_body requires code subtype")
                parts.append(self._render_verbatim(child.content))
            elif isinstance(child, AlgorithmBodyBlock):
                if block.sub_type != RAW_ALGORITHM:
                    raise TypeError("algorithm_body requires algorithm subtype")
                content = render_inline_spans(child.content, self.anchors)
                parts.append("\n".join((r"\begin{quote}", rf"{{\small\ttfamily {content}\par}}", r"\end{quote}")))
            elif isinstance(child, CodeAnnotationBlock):
                parts.append(self._render_annotation(child))
            else:
                raise TypeError(f"Unsupported code child: {type(child).__name__}")
        return _join_parts(parts)

    def _render_annotation(
        self,
        block: ImageAnnotationBlock | TableAnnotationBlock | ChartAnnotationBlock | CodeAnnotationBlock,
    ) -> str:
        """Press caption/footnote discriminator to output the weakening description style."""
        content = render_inline_spans(block.content, self.anchors)
        if not content.strip():
            return ""
        if str(block.type).endswith("caption"):
            return rf"{{\small\itshape {content}\par}}"
        return rf"{{\footnotesize\color{{DocVortexGray}} {content}\par}}"

    def _render_image_payload(self, block: ImagePayloadBlock, *, alt_text: str) -> str:
        """Output local sidecar; other sources are demoted to links or visible placeholders."""
        local = self._render_local_image(block)
        if local:
            return local
        label = self._placeholder(f"image unavailable: {alt_text}")
        remote_url = remote_block_image_url(block)
        if remote_url:
            return rf"\href{{{escape_latex_url(remote_url)}}}{{{label}}}\par"
        return label + r"\par"

    def _render_local_image(self, block: ImagePayloadBlock) -> str:
        """If there is a safe sidecar supported by XeLaTeX, a bounded includegraphics is generated."""
        path = resolve_block_image_path(block, self.asset_base_path)
        if path is None:
            return ""
        return (
            rf"\noindent\includegraphics[width=\linewidth,height=.8\textheight,keepaspectratio]"
            rf"{{{tex_image_path(path)}}}\par"
        )

    def _placeholder(self, message: str) -> str:
        """Generate stable visible placeholders that do not expose binary payloads."""
        return rf"\DocVortexPlaceholder{{{escape_latex_text(message, preserve_newlines=False)}}}"

    def _render_verbatim(self, content: str) -> str:
        """Select a unique fvextra environment for each preformatted block where the text cannot be closed early."""
        normalized = content.replace("\r\n", "\n").replace("\r", "\n")
        while True:
            self.verbatim_counter += 1
            environment = f"DocVortexVerbatim{self.verbatim_counter}"
            if rf"\end{{{environment}}}" not in normalized:
                break
        definition = (
            rf"\DefineVerbatimEnvironment{{{environment}}}{{Verbatim}}"
            r"{breaklines=true,breakanywhere=true,fontsize=\small}"
        )
        return "\n".join((definition, rf"\begin{{{environment}}}", normalized, rf"\end{{{environment}}}"))


def render_latex(
    middle_json: MiddleJson,
    *,
    asset_base_path: str = "",
    document_title: str | None = None,
) -> str:
    """Render strictly pure functional MiddleJson into TeX Live XeLaTeX complete source code."""
    if not isinstance(middle_json, MiddleJson):
        raise TypeError("render_latex expects a MiddleJson instance")
    if not isinstance(asset_base_path, str):
        raise TypeError("asset_base_path must be a string")
    if document_title is not None and not isinstance(document_title, str):
        raise TypeError("document_title must be a string or None")
    return _LatexRenderer(
        middle_json,
        asset_base_path=asset_base_path,
        document_title=document_title,
    ).render()


def _resolve_document_title(middle_json: MiddleJson, explicit: str | None) -> str:
    """Parses metadata title by explicit title, first document title, and fixed fallback value."""
    if explicit is not None and explicit.strip():
        return explicit.strip()
    for page in middle_json.pages:
        for block in page.blocks:
            if isinstance(block, DocTitleBlock):
                title = inline_plain_text(block.content).strip()
                if title:
                    return title
    return "DocVortex Document"


def _collect_anchor_targets(middle_json: MiddleJson) -> set[str]:
    """Collect actual visible text, titles and page footers anchor."""
    targets: set[str] = set()
    for page in middle_json.pages:
        for block in page.blocks:
            if not isinstance(block, (TextBlock, TitleBlockBase, PageFootnoteBlock)):
                continue
            anchor = (block.anchor or "").strip()
            if anchor and inline_plain_text(block.content).strip():
                targets.add(anchor)
    return targets


def _classify_list(items: list[ListItem], add_reference_bullets: bool) -> tuple[str, str]:
    """Select the LaTeX list environment and content policy based on the direct marker selection."""
    if add_reference_bullets:
        return "itemize", "reference"
    if items and all(item.kind == "unordered" for item in items):
        return "itemize", "unordered"
    if items and all(item.kind == "ordered" for item in items):
        styles = {item.ordered_style for item in items}
        if len(styles) == 1:
            return "enumerate", "ordered"
    if items and all(item.kind == "none" for item in items):
        return "itemize", "unmarked"
    return "description", "explicit"


def _list_item_content(
    item: ListItem,
    original: list[InlineSpan],
    kind: str,
    add_reference_bullets: bool,
) -> tuple[list[InlineSpan], str | None]:
    """Determines whether list items should be stripped, retained, or the source marker should be shown explicitly."""
    if add_reference_bullets:
        return (item.body, None) if item.kind == "unordered" else (original, None)
    if kind == "unordered":
        return item.body, None
    if kind == "ordered":
        return item.body, item.marker
    if kind == "unmarked":
        return item.body, None
    return item.body, item.marker


def _paragraph(content: str) -> str:
    """Consolidate the source code in non-blank lines into an ordinary LaTeX paragraph."""
    return f"{content}\\par" if content.strip() else ""


def _wrap_display_formula(content: str) -> str:
    """Keep the complete AMS display environment, and put other bare formulas into equation*."""
    match = _TOP_LEVEL_DISPLAY_ENV_RE.match(content)
    if match is not None and content.rstrip().endswith(rf"\end{{{match.group('name')}}}"):
        return content
    return "\n".join((r"\begin{equation*}", content, r"\end{equation*}"))


def _join_parts(parts: list[str]) -> str:
    """Concatenate all non-empty LaTeX clips in subchunk source order."""
    return "\n\n".join(part for part in parts if part and part.strip())


def _plain_html_text(content: str) -> str:
    """Extract visible text from HTML or a normal string for use by alternative information."""
    if not content:
        return ""
    return BeautifulSoup(content, "html.parser").get_text("\n", strip=True)


def _has_image_payload(block: ImagePayloadBlock) -> bool:
    """Determine whether block declares any kind of image source."""
    return bool(block.image_path or block.image_base64 or block.image_url)


__all__ = ["render_latex"]
