"""Pure value conversion between geometric loads and independent rectangle types."""

from __future__ import annotations

from ._contracts import Bbox


def char_bbox_values(bbox: object) -> tuple[float, float, float, float] | None:
    """Read fixed four-dimensional coordinates and reject geometric objects with incomplete structures."""
    if isinstance(bbox, Bbox):
        bbox = bbox.bbox
        # The built-in floating point box generated by native extraction has completed numerical conversion and can be read directly to avoid repeated calls to float.
        if (
            type(bbox) is list
            and len(bbox) == 4
            and type(bbox[0]) is float
            and type(bbox[1]) is float
            and type(bbox[2]) is float
            and type(bbox[3]) is float
        ):
            return bbox[0], bbox[1], bbox[2], bbox[3]
    if isinstance(bbox, (tuple, list)) and len(bbox) == 4:
        return tuple(float(value) for value in bbox)
    return None


__all__ = ["char_bbox_values"]
