"""Native PDF Neutral internal data contract used by table structure recovery."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from .....document.pdf.text._contracts import Char
from .....schema import BBox

NativeTableCandidateSource = Literal[
    "vector_grid",
    "sparse_hybrid",
    "sparse_multiline",
    "sparse_grid",
    "text_grid",
    "key_value",
]


class PDFTableRecoveryError(RuntimeError):
    """Marks failures in the structure recovery phase for the host to distinguish rollback errors from HTML materialization exceptions."""


@dataclass(frozen=True, slots=True)
class NativeTableRule:
    """Saves a visible horizontal or vertical line in page coordinates."""

    bbox: BBox
    width: float
    orientation: Literal["horizontal", "vertical"]


@dataclass(frozen=True, slots=True)
class NativeTableRectangle:
    """Saves the PDF rectangular path and its draw properties in page coordinates."""

    bbox: BBox
    segment_count: int
    fill_visible: bool
    stroke_visible: bool
    form_depth: int = 0


@dataclass(frozen=True, slots=True)
class NativeTableInput:
    """Saves all page primitives required for a known table region structure recovery."""

    table_bbox: BBox
    page_size: tuple[float, float]
    angle: int
    chars: tuple[Char, ...]
    drawing_lines: tuple[NativeTableRule, ...] = field(default_factory=tuple)
    rectangles: tuple[NativeTableRectangle, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class NativeTableGlyph:
    """Saves a single visible PDF character in forward table local coordinates."""

    glyph_id: int
    source_index: int
    text: str
    bbox: BBox
    visual_row: int
    explicit_space_before: bool = False
    explicit_break_before: bool = False


@dataclass(frozen=True, slots=True)
class NativeTableToken:
    """Saves tabular text items consisting of consecutive characters within the same visual line."""

    text: str
    bbox: BBox
    glyph_ids: tuple[int, ...]
    source_char_indices: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class NativeTableTextRow:
    """Saves a visual text line in table local coordinates."""

    row_index: int
    bbox: BBox
    tokens: tuple[NativeTableToken, ...]
    glyph_ids: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class NativeTableText:
    """Save the glyph, text line and scale statistics after unified character preprocessing."""

    glyphs: tuple[NativeTableGlyph, ...]
    rows: tuple[NativeTableTextRow, ...]
    median_glyph_width: float
    median_glyph_height: float


@dataclass(frozen=True, slots=True)
class NativeTableCell:
    """Saves the grid position, content, and character source of a logical cell."""

    row: int
    col: int
    rowspan: int
    colspan: int
    bbox: BBox
    content: str
    source_char_indices: tuple[int, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class NativeTableCandidate:
    """Save the table candidates generated by the single-pass algorithm and with completed text placement."""

    source: NativeTableCandidateSource
    rows: int
    cols: int
    cells: tuple[NativeTableCell, ...]
    score: float
    text_capture: float
    structure_support: float
    row_stability: float
    column_stability: float
    order_consistency: float
    issues: tuple[str, ...] = field(default_factory=tuple)

    @property
    def topology(self) -> tuple[int, int, tuple[tuple[int, int, int, int], ...]]:
        """Returns a stable topological signature without text for candidate conflict arbitration."""

        spans = tuple(sorted((cell.row, cell.col, cell.rowspan, cell.colspan) for cell in self.cells))
        return self.rows, self.cols, spans


@dataclass(frozen=True, slots=True)
class NativeTableResult:
    """Save the final adopted native table HTML and its diagnostic internal structure."""

    html: str
    rows: int
    cols: int
    cells: tuple[NativeTableCell, ...]
    text: NativeTableText
    source: NativeTableCandidateSource
    confidence: float
    diagnostics: tuple[str, ...] = field(default_factory=tuple)


__all__ = [
    "NativeTableCell",
    "NativeTableInput",
    "NativeTableRectangle",
    "NativeTableResult",
    "NativeTableRule",
]
